export const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  HOTEL_MANAGER: 'HOTEL_MANAGER',
  FRONT_DESK: 'FRONT_DESK',
  HOUSEKEEPING: 'HOUSEKEEPING',
  MAINTENANCE: 'MAINTENANCE',
  FINANCE: 'FINANCE',
} as const;

export type RoleName = (typeof ROLES)[keyof typeof ROLES];

export const PERMISSIONS = {
  USERS_READ: 'users.read',
  USERS_UPDATE: 'users.update',
  RESERVATIONS_READ: 'reservations.read',
  RESERVATIONS_UPDATE: 'reservations.update',
  ROOMS_READ: 'rooms.read',
  ROOMS_UPDATE: 'rooms.update',
  BILLING_READ: 'billing.read',
  BILLING_UPDATE: 'billing.update',
} as const;

export type PermissionName = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const ALL_PERMISSIONS: PermissionName[] = Object.values(PERMISSIONS);

export const ROLE_PERMISSIONS: Record<RoleName, PermissionName[]> = {
  [ROLES.SUPER_ADMIN]: ALL_PERMISSIONS,
  [ROLES.HOTEL_MANAGER]: ALL_PERMISSIONS,
  [ROLES.FRONT_DESK]: [
    PERMISSIONS.USERS_READ,
    PERMISSIONS.RESERVATIONS_READ,
    PERMISSIONS.RESERVATIONS_UPDATE,
    PERMISSIONS.ROOMS_READ,
  ],
  [ROLES.HOUSEKEEPING]: [PERMISSIONS.ROOMS_READ, PERMISSIONS.ROOMS_UPDATE],
  [ROLES.MAINTENANCE]: [PERMISSIONS.ROOMS_READ, PERMISSIONS.ROOMS_UPDATE],
  [ROLES.FINANCE]: [
    PERMISSIONS.BILLING_READ,
    PERMISSIONS.BILLING_UPDATE,
    PERMISSIONS.RESERVATIONS_READ,
  ],
};
