export const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  HOTEL_MANAGER: 'HOTEL_MANAGER',
  FRONT_DESK: 'FRONT_DESK',
  HOUSEKEEPING: 'HOUSEKEEPING',
  MAINTENANCE: 'MAINTENANCE',
  FINANCE: 'FINANCE',
} as const;

export type RoleName = (typeof ROLES)[keyof typeof ROLES];

export const PERMISSIONS = {
  USERS_READ: 'users.read',
  USERS_UPDATE: 'users.update',
  GUESTS_READ: 'guests.read',
  GUESTS_WRITE: 'guests.write',
  RESERVATIONS_READ: 'reservations.read',
  RESERVATIONS_WRITE: 'reservations.write',
  HOTELS_READ: 'hotels.read',
  HOTELS_WRITE: 'hotels.write',
  ROOMS_READ: 'rooms.read',
  ROOMS_WRITE: 'rooms.write',
  AMENITIES_READ: 'amenities.read',
  AMENITIES_WRITE: 'amenities.write',
  HOUSEKEEPING_READ: 'housekeeping.read',
  HOUSEKEEPING_WRITE: 'housekeeping.write',
  MAINTENANCE_READ: 'maintenance.read',
  MAINTENANCE_WRITE: 'maintenance.write',
  BILLING_READ: 'billing.read',
  BILLING_WRITE: 'billing.write',
} as const;

export type PermissionName = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const ALL_PERMISSIONS: PermissionName[] = Object.values(PERMISSIONS);

export const ROLE_PERMISSIONS: Record<RoleName, PermissionName[]> = {
  [ROLES.SUPER_ADMIN]: ALL_PERMISSIONS,
  [ROLES.HOTEL_MANAGER]: ALL_PERMISSIONS,
  [ROLES.FRONT_DESK]: [
    PERMISSIONS.USERS_READ,
    PERMISSIONS.GUESTS_READ,
    PERMISSIONS.GUESTS_WRITE,
    PERMISSIONS.RESERVATIONS_READ,
    PERMISSIONS.RESERVATIONS_WRITE,
    PERMISSIONS.HOTELS_READ,
    PERMISSIONS.ROOMS_READ,
    PERMISSIONS.AMENITIES_READ,
    PERMISSIONS.HOUSEKEEPING_READ,
    PERMISSIONS.MAINTENANCE_READ,
  ],
  [ROLES.HOUSEKEEPING]: [
    PERMISSIONS.ROOMS_READ,
    PERMISSIONS.ROOMS_WRITE,
    PERMISSIONS.AMENITIES_READ,
    PERMISSIONS.HOUSEKEEPING_READ,
    PERMISSIONS.HOUSEKEEPING_WRITE,
  ],
  [ROLES.MAINTENANCE]: [
    PERMISSIONS.ROOMS_READ,
    PERMISSIONS.ROOMS_WRITE,
    PERMISSIONS.AMENITIES_READ,
    PERMISSIONS.MAINTENANCE_READ,
    PERMISSIONS.MAINTENANCE_WRITE,
  ],
  [ROLES.FINANCE]: [
    PERMISSIONS.BILLING_READ,
    PERMISSIONS.BILLING_WRITE,
    PERMISSIONS.GUESTS_READ,
    PERMISSIONS.RESERVATIONS_READ,
    PERMISSIONS.HOTELS_READ,
    PERMISSIONS.ROOMS_READ,
  ],
};
